### PR TITLE
Fix magit-section usage so the expand/contract functionality works

### PR DESCRIPTION
**Pull request by bustercopley**
Use named sections so magit-section can track which sections are expanded.
Don't use sections for individual diagnostics, since they can't be tracked.
Capture data in lexicals for deferred rendering by `magit-insert-section-body`.
Use `with-current-buffer` (delete `lean4-with-info-output-to-buffer`).
Make the diagnostic `line:col` headers into text buttons.

### CODE REVIEW

**Comment by bustercopley** [comment]
force-push: rebase onto #51

**Comment by bustercopley** [comment]
rebase onto [leanprover-community:master](https://github.com/leanprover-community/lean4-mode/tree/master)

**Comment by sebeaumont** [comment]
Can someone merge this please?

**Comment by bustercopley** [comment]
I see no reason not to. It's just a minor bugfix. @sebeaumont, please ping Yuri (@urkud) on Zulip.

**Pull request merged**
